version: '3'

services: 
    
    web:

        container_name: gestion_etudiants

        build: 

            context: ../gestion_etudiants/docker/web

        ports: 
          
            - 8000:8000
        volumes: 

            - ./:/var/www/app

        container_name: gestion_events

        build: 
    
            context: ../gestion_events/docker/web
    
        ports: 
              
            - 8001:8001
        volumes: 
    
            - ./:/var/www/app    